name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --assume-yes --no-install-recommends ca-certificates build-essential git googletest libgtest-dev
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          make recsplit ranksel fenwick dynranksel
